-- HoopSwap seed data: 4 categories, 5 products each (20 products total).

-- Categories -----------------------------------------------------------------
INSERT INTO categories (id, name, description) VALUES
    (1, 'Sneakers',    'Basketball shoes, new and pre-loved — signature models and team editions.'),
    (2, 'Jerseys',     'NBA and team jerseys — authentic, swingman, and replica styles.'),
    (3, 'Balls',       'Indoor game balls, outdoor street balls, and training balls.'),
    (4, 'Accessories', 'Headbands, sleeves, socks, bags and other on-court essentials.');

-- Sneakers (category 1) ------------------------------------------------------
INSERT INTO products (category_id, name, description, price, image_name) VALUES
    (1,
     'Nike LeBron XXI',
     'The latest flagship signature shoe for King James, featuring Nike Air Max Zoom cushioning and a lightweight Fuse Fiber upper. Worn for one season in excellent condition, size US 10.5. Built for explosive drives and lockdown defense on any hardwood. Original box and dust bag included.',
     220.00,
     'lebron_xxi.jpg'),
    (1,
     'Adidas Dame 8',
     'Damian Lillard''s eighth signature shoe with Lightstrike cushioning and a supportive midfoot cage. Size US 11, lightly used on indoor courts only. Responsive and low-to-the-ground feel that guards love. Clean outsole with minimal creasing.',
     140.00,
     'dame_8.jpg'),
    (1,
     'Jordan Luka 2',
     'Luka Doncic''s second signature Jordan Brand release with Formula 23 foam cushioning. Brand new in box, size US 9, never laced up. Built for multi-directional play, quick cuts, and step-back threes. Great colourway for on-court or casual wear.',
     175.00,
     'luka_2.jpg'),
    (1,
     'Nike KD 16',
     'Kevin Durant''s sixteenth signature shoe featuring full-length Zoom Air cushioning and a breathable knit upper. Pre-loved, size US 12, used for about two months of pickup games. Smooth, bouncy ride well suited to wings and forwards. Minor scuffing on the toe box, otherwise solid.',
     160.00,
     'kd_16.jpg'),
    (1,
     'Under Armour Curry Flow 11',
     'Steph Curry''s latest signature with UA Flow cushioning and a rubberless outsole for unmatched court feel. Size US 10, worn only on indoor hardwood. Known for best-in-class traction and an ultra-lightweight build. Comes with original laces and carry bag.',
     190.00,
     'curry_11.jpg');

-- Jerseys (category 2) -------------------------------------------------------
INSERT INTO products (category_id, name, description, price, image_name) VALUES
    (2,
     'Lakers LeBron James #23',
     'Official Nike Swingman jersey in the Lakers purple and gold Icon Edition, size Large. Screen-printed name and number, lightly worn and freshly laundered. Perfect for game days, pick-up runs, or wall display. No pilling, no fading — reads as near-new.',
     95.00,
     'jersey_lebron.jpg'),
    (2,
     'Warriors Stephen Curry #30',
     'Authentic Nike Icon Edition Warriors jersey, size Medium, Chef Curry''s classic Royal Blue. Great condition with only minimal wash wear. Ideal for fans of the Splash Brothers dynasty era. Tagless neck label for extra comfort.',
     90.00,
     'jersey_curry.jpg'),
    (2,
     'Celtics Jayson Tatum #0',
     'Nike Swingman Tatum jersey in classic Celtics Kelly green, size Large. Brand new with tags, never worn. Support the current Boston franchise star with breathable Dri-FIT mesh construction. Screen-printed graphics sit cleanly and centred.',
     110.00,
     'jersey_tatum.jpg'),
    (2,
     'Bucks Giannis Antetokounmpo #34',
     'Milwaukee Bucks Icon Edition Giannis jersey, size XL, in the good green-and-cream colourway. Heat-applied numbers and crest in excellent condition. Celebrate the Greek Freak in style at the arena or on the couch. Light wash wear only.',
     75.00,
     'jersey_giannis.jpg'),
    (2,
     'Nuggets Nikola Jokic #15',
     'Denver Nuggets Jokic jersey, size Large, classic navy colourway. MVP-grade gear in near-new condition — worn for one parade only. Soft, lightweight mesh with embroidered team crest. A must for Nuggets faithful.',
     100.00,
     'jersey_jokic.jpg');

-- Balls (category 3) ---------------------------------------------------------
INSERT INTO products (category_id, name, description, price, image_name) VALUES
    (3,
     'Spalding NBA Official Game Ball',
     'Full-grain leather indoor game ball as used in the NBA, size 7 (29.5 inches). Broken in on real hardwood so grip is perfect from the first dribble. For indoor use only — do not bounce on concrete. Includes a free pump and needle.',
     120.00,
     'spalding_nba.jpg'),
    (3,
     'Wilson Evolution Indoor',
     'The classic high school and college indoor basketball with composite leather cover, size 7. Soft feel and consistent grip, lightly used in a school gym. A popular choice for serious indoor players who want a pro feel. Retains shape and bounce like new.',
     85.00,
     'wilson_evo.jpg'),
    (3,
     'Molten BG5000 FIBA Ball',
     'Official FIBA international competition ball with the distinctive twelve-panel composite leather design, size 7. Pre-loved but well cared for, no flat spots. Twelve-panel pattern improves rotational visibility for shooters. Great for training, drills, or league matches.',
     95.00,
     'molten_bg5000.jpg'),
    (3,
     'Spalding Street Outdoor',
     'Durable rubber outdoor ball built for asphalt and concrete courts, size 7. Some visible wear from playground use but still bounces true and holds air. An affordable, reliable option for street hoops and driveway games. Weather-resistant construction.',
     35.00,
     'spalding_street.jpg'),
    (3,
     'Under Armour 495 Training Ball',
     'Heavier-than-standard training basketball designed to build hand strength and improve ball control, size 7. Great for form shooting and ball-handling drills. Barely used, essentially new condition. Includes a UA drawstring bag.',
     40.00,
     'ua_495.jpg');

-- Accessories (category 4) ---------------------------------------------------
INSERT INTO products (category_id, name, description, price, image_name) VALUES
    (4,
     'Nike Pro Compression Arm Sleeve',
     'Nike Pro Dri-FIT compression arm sleeve in black, adult size L/XL. Provides muscle support and sweat-wicking during play. Lightly used, washed and clean with strong elasticity. Ideal for shooters or anyone recovering from an elbow knock.',
     25.00,
     'nike_sleeve.jpg'),
    (4,
     'Adidas Basketball Headband',
     'Adidas Interval reversible headband in black/white, one size fits most. Absorbs sweat and keeps hair in check during intense runs. Brand new, still in packaging, with a soft elastic band. An essential kit piece for active players.',
     18.00,
     'adidas_headband.jpg'),
    (4,
     'Nike Elite Crew Socks',
     'Nike Elite cushioned basketball crew socks in white, size Large — pack of two pairs, lightly worn. Targeted Zoned Cushioning and Dri-FIT construction keep feet dry and protected. A favourite of on-court players for comfort and grip. Machine washable.',
     35.00,
     'nike_socks.jpg'),
    (4,
     'Under Armour Basketball Backpack',
     'UA Undeniable 5.0 backpack in black with a dedicated ball compartment and padded 15-inch laptop sleeve. Used for one school semester, clean inside and out. Perfect for carrying gear from class to practice. Water-resistant abrasion-proof base.',
     65.00,
     'ua_backpack.jpg'),
    (4,
     'Spalding Ball Pump with Needles',
     'Dual-action hand pump that works for basketballs, footballs, and soccer balls. Includes three spare inflation needles and a flexible hose attachment. Brand new, never used. An essential accessory for any home court or team kit bag.',
     15.00,
     'spalding_pump.jpg');
